#!/bin/bash

#. _common.sh ${BASH_SOURCE[0]}

#[[ ! -f "/dev/$1" ]] && echo invalid disk && exit 1
DISK_DEV=$1

# find image backup path
for postfix in "1" ""
do
    BACKUP_DIR=/media/${USER}/Expansion${postfix}/disk_backup
    echo ${BACKUP_DIR}
    [[ -d "${BACKUP_DIR}" ]] && break
done
BACKUP_DIR=/media/${USER}/SSD/disk_backup
[[ ! -d "${BACKUP_DIR}" ]] && echo no image backup destination && exit 1

# get disk serial and size
DISK_SERIAL=$(udevadm info --query=all --name=/dev/${DISK_DEV} | grep ID_SERIAL= | sed -e 's/^.*=//g')
DISK_SIZE=$(numfmt --to iec --format "%8.4f" $(sudo blockdev --getsz /dev/${DISK_DEV}))

# file with image backups, used to get a unique id (line number)
#IMG_LIST_FILE=${BACKUP_DIR}/imglist.txt
#[ ! -f "${IMG_LIST_FILE}" ] && touch ${IMG_LIST_FILE}

IMG_FILE_NAME=${DISK_SERIAL/:/-}
echo $IMG_FILE_NAME
if compgen -G "${BACKUP_DIR}/${IMG_FILE_NAME}*" > /dev/null; then
    echo "image file exists"
    exit 1
fi

TGT_DIR=/media/${USER}/SSD

echo sudo ddrescue -d -r0 -e +0 -T 1s -n /dev/$1 ${TGT_DIR}/${IMG_FILE_NAME}.img ${TGT_DIR}/${IMG_FILE_NAME}.logfile
[[ ! -z "$2" ]] && exit 1
sudo ddrescue -d -r0 -n /dev/$1 ${TGT_DIR}/${IMG_FILE_NAME}.img ${TGT_DIR}/${IMG_FILE_NAME}.logfile
~/zstd -9 ${TGT_DIR}/${IMG_FILE_NAME}.img -o ${BACKUP_DIR}/${IMG_FILE_NAME}.img.zst
